"""Markdown report generation for pipeline execution summaries."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from agentix.pipeline import Pipeline
from agentix.kanban import KanbanBoard


def generate_pipeline_report(
    pipeline: Pipeline,
    board: Optional[KanbanBoard] = None,
    context: Optional[Dict[str, Any]] = None,
    metrics: Optional[Dict[str, Any]] = None,
) -> str:
    """Generate a Markdown report for a pipeline execution.

    Parameters
    ----------
    pipeline : Pipeline
        The pipeline definition.
    board : KanbanBoard, optional
        Board state to include in the report.
    context : dict, optional
        Pipeline context/outputs.
    metrics : dict, optional
        Stage timing metrics.

    Returns
    -------
    str
        Markdown-formatted report.
    """
    lines: List[str] = []
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    # Header
    lines.append(f"# Pipeline Report: {pipeline.name}")
    lines.append(f"**Generated:** {timestamp}")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append(f"- **Pipeline:** {pipeline.name}")
    lines.append(f"- **Stages:** {len(pipeline.stages)}")
    if metrics:
        total_time = metrics.get("total_time", 0)
        avg_time = metrics.get("average_time", 0)
        lines.append(f"- **Total execution time:** {total_time:.2f}s")
        lines.append(f"- **Average stage time:** {avg_time:.2f}s" if avg_time else "")
    lines.append("")

    # Stages
    lines.append("## Stages")
    for i, stage in enumerate(pipeline.stages, 1):
        name = stage["name"]
        agent = stage.get("agent_type", "?")
        deps = stage.get("depends_on", [])
        inputs = stage.get("input_keys", [])
        outputs = stage.get("output_keys", [])

        lines.append(f"### {i}. {name}")
        lines.append(f"- **Agent:** {agent}")
        if deps:
            lines.append(f"- **Depends on:** {', '.join(deps)}")
        if inputs:
            lines.append(f"- **Inputs:** {', '.join(inputs)}")
        if outputs:
            lines.append(f"- **Outputs:** {', '.join(outputs)}")
        lines.append("")

    # Board state
    if board:
        state = board.get_board_state()
        lines.append("## Board State")
        for col in board.VALID_COLUMNS:
            tasks = state.get(col, [])
            col_name = col.replace("_", " ").title()
            if tasks:
                lines.append(f"### {col_name} ({len(tasks)})")
                for task in tasks:
                    lines.append(f"- **{task.get('title', '?')}** (id: `{task.get('id', '?')}`, agent: `{task.get('agent', '?')}`)")
                lines.append("")
            else:
                lines.append(f"### {col_name} (0)")
                lines.append("")

    # Context outputs
    if context:
        lines.append("## Output Context")
        for key, value in context.items():
            val_str = str(value)
            if len(val_str) > 200:
                val_str = val_str[:200] + "..."
            lines.append(f"- **{key}:** `{val_str}`")
        lines.append("")

    # Metrics detail
    if metrics:
        lines.append("## Metrics")
        by_status = metrics.get("by_status", {})
        if by_status:
            lines.append("### Stage Status Distribution")
            for status, count in by_status.items():
                lines.append(f"- **{status}:** {count}")
            lines.append("")

        slowest = metrics.get("slowest", [])
        if slowest:
            lines.append("### Slowest Stages")
            for s in slowest:
                dur = s.get("duration_seconds", 0)
                lines.append(f"- **{s.get('stage_name', '?')}** ({s.get('agent_type', '?')}): {dur:.2f}s")
            lines.append("")

    # Dependency graph visualization
    lines.append("## Dependency Graph")
    lines.append("```mermaid")
    lines.append("flowchart LR")
    for stage in pipeline.stages:
        nid = stage["name"].replace(" ", "_")
        lines.append(f"    {nid}[\"{stage['name']}\"]")
    for stage in pipeline.stages:
        nid = stage["name"].replace(" ", "_")
        for dep in stage.get("depends_on", []):
            did = dep.replace(" ", "_")
            lines.append(f"    {did} --> {nid}")
    lines.append("```")
    lines.append("")

    lines.append("---")
    lines.append(f"*Report generated by agentix v0.1.0*")

    return "\n".join(lines)


def generate_board_report(board: KanbanBoard) -> str:
    """Generate a Markdown summary of a Kanban board.

    Parameters
    ----------
    board : KanbanBoard
        The board to summarize.

    Returns
    -------
    str
        Markdown-formatted board summary.
    """
    lines: List[str] = []
    lines.append(f"# Kanban Board: {board.name}")
    lines.append("")

    state = board.get_board_state()

    for col in board.VALID_COLUMNS:
        tasks = state.get(col, [])
        col_name = col.replace("_", " ").title()
        lines.append(f"## {col_name} ({len(tasks)})")
        if tasks:
            for task in tasks:
                lines.append(f"- [{task.get('priority', 'MEDIUM')}] **{task.get('title', '?')}** - `{task.get('agent', '?')}`")
        else:
            lines.append("*Empty*")
        lines.append("")

    return "\n".join(lines)
